### ISSUE TITLE
account_sid issues (I think?)

### ISSUE THREAD

**Issue by nolancruiser** [simonsanvil/GTP3-whatsapp-chatbot#10]
Hey hey, thanks for the update. Dont know what im doing wrong, but the code just wont work for me. 
python3 -m app.whatsapp does this:
![python3 -m app whatsapp](https://user-images.githubusercontent.com/112344215/222936290-282c8202-81f4-4e16-b3ce-4c5c9d53a0bf.png)
python -m app.whatsapp gives me the following:
![Screenshot 2023-03-04 190707](https://user-images.githubusercontent.com/112344215/222936271-80740cc9-51f2-48c8-8819-781308a9901f.png)
And the appearing problems are these:
![Screenshot 2023-03-04 190724](https://user-images.githubusercontent.com/112344215/222936281-3517877b-e510-4ecd-b359-dabc61bc7d3f.png)

Im doing everything with an .env file and Python 3.10.4 64-bit

**Comment by simonsanvil** [comment]
It looks like your `TWILIO_ACCOUNT_SID` and `TWILIO_ACCOUNT_TOKEN` environmental variables are not being read. Ensure your `.env` file is in the same working directory as when you start your application.

Your second picture is unrelated to the error you are getting. It only affects the demo jupyter notebook  (which needs to be updated with the latest changes)

**Comment by eladrave** [comment]
I think I figured it out - change "TWILIO" to "TWILLIO" in the env
(or change the code, but this is easier)

**Comment by nolancruiser** [comment]
> I think I figured it out - change "TWILIO" to "TWILLIO" in the env (or change the code, but this is easier)

This worked! still havent been able to get the bot to reply to me but hey at least now it runs. thank you so much!

**Comment by eladrave** [comment]
You can use Repl.it to run it "in the cloud".

Just make sure you put the env vars in the Secrets section of the Repl.

I did that, and no code change. Still working

**Comment by nolancruiser** [comment]
> You can use Repl.it to run it "in the cloud".
> 
> Just make sure you put the env vars in the Secrets section of the Repl.
> 
> I did that, and no code change. Still working

Like this? 

![secretsrepl](https://user-images.githubusercontent.com/112344215/223852300-7ad15e42-9111-4a69-a9d3-f66d5ed403d1.png)

**Comment by eladrave** [comment]
No,
You need to turn it into a JSON format.
Just ask ChatGPT to do it for you :)

**Comment by nolancruiser** [comment]
okok, this is the conversion chatgpt is giving me, for some reason repl dosent like it
I asked chatgpt and its giving me generic incorrect answers 
Any idea why this may be happening?

![make sure that all values are strings](https://user-images.githubusercontent.com/112344215/223870775-28d06482-ee76-4695-a629-e00617a84411.png)

**Comment by eladrave** [comment]
First - don't forget to change the .replit config file - add this: run="python3 -m app.whatsapp"

And comment all the [interpreter] section.

As for the JSON - this is the format:

{
  "FROM_WHATSAPP_NUMBER": "+1231231234",
  "OPENAI_API_KEY": "sk-NmKN3JSDHUJNKDHSK3543Wsy4ra3gbq9",
  "CHAT_MODEL": "gpt-3.5-turbo",
  "APP_PORT": "5000",
  "APP_HOST": "0.0.0.0",
  "ASSEMBLYAI_API_KEY": "",
  "CHAT_START_TEMPLATE": "data/start_templates/img_generation_assistant.txt",
  "MAX_TOKENS": "1000",
  "TWILLIO_AUTH_TOKEN": "3bTHISISMYTOKEN0EB",
  "TWILLIO_ACCOUNT_SID": "AC6fhaTHISISMYSID4c122"
}

**Comment by nolancruiser** [comment]
Hey hey, been trying this for a couple of days now but I just cant get it to run for some reason... Did everything correctly (I think) but I guess im not experienced enough to catch the small errors. 

Heres the link (https://replit.com/join/tvsykgsgkx-nolancruiser)

Please let me know if you spot anything thats wrong

**Comment by eladrave** [comment]
Hi,

I accessed your Repl.
I fixed your start command, and it can start now.
However, it seems like your folder structure is wrong.

I suggest you start by pulling the repository to an empty Repl.

[image: Screen Shot 2023-03-11 at 12.29.36 PM.png]
When starting the new Repl - start by importing from GitHub, the top right.
Then you should configure the new Repl (see what I did with the "Repl"
file, or just copy it)

Then,
Set up the env vars.

Then you need to change the config to run the module.

**Comment by nolancruiser** [comment]
Hey hey, not able to see the screenshot you sent but I think I did everything correctly, getting this error now:
![Screenshot 2023-03-12 160050](https://user-images.githubusercontent.com/112344215/224576333-06fe3fc2-49ab-42cb-ad55-24501a06ee6d.png)

Heres the repl link https://replit.com/join/hflyrpeqbz-nolancruiser

**Comment by nolancruiser** [comment]
Hey eladrave, been trying to change all sorts of things in the code but nothing seems to work, think I configured the run module incorrectly. 

Please let me know if you see anything wrong in the code, feel like im running in circles and youve been very helpful so far. 

anyway, heres my email if youd rather communicate through there: nolancruiser@gmail.com 

> Then you need to change the config to run the module.
