### ISSUE TITLE
Special command

### ISSUE THREAD

**Issue by eladrave** [simonsanvil/GTP3-whatsapp-chatbot#12]
Hi,

Are there any special commands I can use?
(like %%clear - to clear the convo and start a new one)

**Comment by simonsanvil** [comment]
Hi, Yes. Right now, if you text the bot any of the [end conversation phrases](https://github.com/simonsanvil/openai-whatsapp-chatbot/blob/master/app/whatsapp/chat.py#:~:text=end_conversation_phrases) defined by the chat manager,  it should restart the conversation. You can always change them to the ones you prefer.

**Comment by eladrave** [comment]
Thank you for the quick response
