### ISSUE TITLE
ModuleNotFoundError: No module named 'openai_agent.agent_utils'

### ISSUE THREAD

**Issue by ozkrleal** [simonsanvil/GTP3-whatsapp-chatbot#4]
I'm getting this error when running `python3 -m app.webapp`
Am i missing something? thank you!

**Comment by simonsanvil** [comment]
Hey. The error you are having is because of an import error. The web server part of the application has been deprecated and is no longer supported (I need to update the README). For the perceivable future, I only intend to support the part that works with Whatsapp.
