### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by nolancruiser** [simonsanvil/GTP3-whatsapp-chatbot#9]
I keep getting these erros in VSC, when I run the code it does not work. 
![vscerrors](https://user-images.githubusercontent.com/112344215/220703027-893494df-aba6-4b58-8003-604535597300.png)

When I change the Interpreter from 3.11.2 to 3.10.4 I only get these 
![vscmoreerrors](https://user-images.githubusercontent.com/112344215/220703281-a6768e48-53a2-4b37-857b-8f363865479c.png)

Help

**Comment by simonsanvil** [comment]
Hi. This seems to be mainly because you are inspecting the `app\wepabb` part of the application, which has been deprecated and is severely outdated (see: #4). It also looks like you are missing the installation of some of the required dependencies from `requirements.txt` (e.g. dotenv, requests, flask).

**Comment by nolancruiser** [comment]
I see, thank you for the reply, I cloned the updated code without the webapp part of the application and now I get this problem 
![newesterror](https://user-images.githubusercontent.com/112344215/220753819-dc586c07-99ca-47a7-83b8-a71aa44055cf.png)

**Comment by simonsanvil** [comment]
Oh, my mistake, you can remove or comment that line if you want. I'll update the repo asap

**Comment by nolancruiser** [comment]
Hey hey, I think removing the line is making the whole code not work, VSC marks it as an M. Have been trying for a couple of days and nothing seems to work. Please let me know if you are able to find a fix.

**Comment by simonsanvil** [comment]
ITT this is solved in the last release of the app, so I will close this issue but feel free to reopen it if you encounter any other error.
